### ISSUE TITLE
프로젝트 생성 및 Tuist 초기 설정

### ISSUE THREAD

**Issue by sanghyeok-kim** [LifePoop/LifePoop-iOS#1]
### 💡 이슈 설명

- 프로젝트 생성, Tuist를 이용한 모듈화 초기 설정

<br>

### 📋 해야 할 일

- 프로젝트 파일 생성
- Tuist 파일 작성하여 아키텍처에 맞게 모듈화 (Presentaion / Domain / Data)

**Comment by junu0516** [comment]
깃 크라켄에서 단 코멘트입니다.
